# DeckCPU — top-level build
#
# Phase 2 targets:
#   make compile   Icarus compile of all RTL + testbenches
#   make lint      Verilator lint gate (per testbench)
#   make sim       compile and run every testbench
#   make test      full regression: ISA + docs + lint + sim
#   make docs      regenerate generated docs from isa/isa.json
#   make clean
#
# decoder_tb consumes golden decode vectors generated by tools/isa_tools.py
# from isa/isa.json (build/gen/decoder_vectors.svh); 'make test' regenerates
# and checks them continuously against that single source of truth.
#
# Invalidated artefacts never survive 'make clean'.

SIM       ?= iverilog
SIMFLAGS  ?= -g2012 -Wall
VVP       ?= vvp
VERILATOR ?= verilator

BUILD_DIR ?= build
GEN_DIR   := $(BUILD_DIR)/gen
SIM_DIR   := $(BUILD_DIR)/sim

# deckcpu_pkg must precede every module that uses package types in its ports.
PKG_SRC := rtl/pkg/deckcpu_pkg.sv
RTL_SRCS := $(PKG_SRC) $(shell find rtl -name '*.sv' ! -path 'rtl/pkg/*' | sort)
TB_DIR   := sim/testbenches
TESTS    := pkg_smoke alu regfile decoder branch_cond

ISA_JSON    := isa/isa.json
GEN_HEADER  := $(GEN_DIR)/decoder_vectors.svh
TOOLS       := tools/isa_tools.py tools/check_pkg_isa.py

SIM_BINS := $(addprefix $(SIM_DIR)/,$(TESTS))

.PHONY: all compile lint sim test docs docs-check isa-check vect clean \
        $(addprefix run-,$(TESTS)) $(addprefix lint-,$(TESTS))

all: compile

# ---- generated golden decode vectors ----
vect: $(GEN_HEADER)

$(GEN_HEADER): $(TOOLS) $(ISA_JSON)
	@mkdir -p $(GEN_DIR)
	python3 tools/isa_tools.py vectors $(ISA_JSON) $@

# ---- per-test Icarus simulation binary ----
$(SIM_DIR)/%: $(RTL_SRCS) $(TB_DIR)/%_tb.sv $(GEN_HEADER)
	@mkdir -p $(SIM_DIR)
	$(SIM) $(SIMFLAGS) -I $(GEN_DIR) -o $@ $(RTL_SRCS) $(TB_DIR)/$*_tb.sv

# Per-test run/lint targets are generated explicitly (pattern-rule recipes
# for phony goals behave unpredictably in GNU make 4.3).
define RUN_mk
.PHONY: run-$(1)
run-$(1): $(SIM_DIR)/$(1)
	$(VVP) $(SIM_DIR)/$(1)
	@echo "PASS:$(1)"
endef
$(foreach t,$(TESTS),$(eval $(call RUN_mk,$(t))))

define LINT_mk
.PHONY: lint-$(1)
lint-$(1): $(RTL_SRCS) $(TB_DIR)/$(1)_tb.sv $(GEN_HEADER)
	@mkdir -p $(BUILD_DIR)
	$(VERILATOR) --lint-only -Wall -Wno-fatal -Wno-DECLFILENAME \
		-I$(GEN_DIR) -top-module $(1)_tb $(RTL_SRCS) $(TB_DIR)/$(1)_tb.sv \
		>/dev/null 2>$(BUILD_DIR)/lint-$(1).log || \
		{ cat $(BUILD_DIR)/lint-$(1).log; exit 1; }
	@echo "lint:$(1) OK"
endef
$(foreach t,$(TESTS),$(eval $(call LINT_mk,$(t))))

compile: $(SIM_BINS)

lint: $(addprefix lint-,$(TESTS))
	@echo "verilator lint OK"

sim: $(addprefix run-,$(TESTS))
	@echo "all simulations OK"

# ---- generated docs from the single source of truth ----
docs:
	python3 tools/isa_tools.py docs $(ISA_JSON) docs

docs-check:
	python3 tools/isa_tools.py docs $(ISA_JSON) $(BUILD_DIR)/docs-check
	@diff -q $(BUILD_DIR)/docs-check/isa.md docs/isa.md >/dev/null || { \
		echo "docs/isa.md is out of date (run 'make docs')"; exit 1; }
	@diff -q $(BUILD_DIR)/docs-check/memory-map.md docs/memory-map.md >/dev/null || { \
		echo "docs/memory-map.md is out of date (run 'make docs')"; exit 1; }
	@echo "generated docs in sync"

# ---- host-side ISA validation and RTL<->spec cross-check ----
isa-check:
	python3 tools/isa_tools.py validate $(ISA_JSON)
	python3 tools/check_pkg_isa.py .

test: isa-check docs-check lint sim
	@echo "================ deckcpu test suite PASSED ================"

clean:
	rm -rf $(BUILD_DIR) obj_dir