# DeckCPU top-level build
#
# Targets:
#   make compile   Icarus compile of all RTL + testbenches
#   make lint      Verilator lint gate (per testbench)
#   make sim       compile and run every testbench
#   make test      full regression: ISA + docs + lint + sim + deckos terminal
#   make docs      regenerate generated docs from isa/isa.json
#   make clean
#
# Interactive DeckOS terminal:
#   make run-deckos       build the console netlist sim and attach the host
#                         terminal to its UART (keypresses -> RTL -> CPU
#                         -> DeckOS shell -> RTL -> terminal output)
#   make run-deckos-vcd   same, with a VCD dump (deckos_term.vcd)
#   term-check            deterministic scripted UART round-trip (part of
#                         'make test': the same transport, no human needed)
#
# decoder_tb consumes golden decode vectors generated by tools/isa_tools.py
# from isa/isa.json (build/gen/decoder_vectors.svh); 'make test' regenerates
# and checks them continuously against that single source of truth.
#
# Invalidated artefacts never survive 'make clean'.

SIM       ?= iverilog
SIMFLAGS  ?= -g2012 -Wall
VVP       ?= vvp
VERILATOR ?= verilator

BUILD_DIR ?= build
GEN_DIR   := $(BUILD_DIR)/gen
SIM_DIR   := $(BUILD_DIR)/sim

# deckcpu_pkg must precede every module that uses package types in its ports.
PKG_SRC := rtl/pkg/deckcpu_pkg.sv
RTL_SRCS := $(PKG_SRC) $(shell find rtl -name '*.sv' ! -path 'rtl/pkg/*' | sort)
TB_DIR   := sim/testbenches
PROG_DIR := sim/programs
PROG_SVHS := $(wildcard $(PROG_DIR)/*_words.svh)
TESTS    := pkg_smoke alu regfile decoder branch_cond cpu_fsm cpu ram bus soc uart timer gpio spi irq deckos deckos_c cshell

# Assembler/disassembler test suite (pytest)
ASM_TEST := software/assembler/test_assembler.py

# deckc CIOS image: BSP + test main + verbatim DeckOS syslog.c -> golden
# .hex/.svh artefacts for deckos_c_tb.sv. Regenerates on ANY change to the
# deckc runtime/BSP/compiler inputs or the vendored DeckOS plain C sources.
CIOS_IMG   := $(PROG_DIR)/cdecko_cios_words.svh
CIOS_HEX   := $(PROG_DIR)/cdecko_cios.hex
CIOS_SRCS  := $(wildcard software/deckc/bsp/* software/deckc/rt/crt0.s \
               sim/programs/cdecko/include/syslog.h \
               sim/programs/cdecko/kernel/syslog.c software/deckc/*.py) \
               tools/gen_cios_image.py

# deckc cshell image: BSP + string.c + the interactive console app + DeckOS
# syslog.c -> golden .hex/.svh artefacts for cshell_tb.sv and cshell_term_tb.sv.
# Regenerates on ANY change to the console app, deckc toolchain/runtime or the
# vendored DeckOS C sources (same policy as CIOS).
CSHELL_IMG   := $(PROG_DIR)/cdecko_cshell_words.svh
CSHELL_HEX   := $(PROG_DIR)/cdecko_cshell.hex
CSHELL_SRCS  := $(wildcard software/deckc/app/* software/deckc/bsp/* \
                 software/deckc/rt/crt0.s \
                 sim/programs/cdecko/include/syslog.h \
                 sim/programs/cdecko/kernel/syslog.c software/deckc/*.py) \
                 tools/gen_cshell_image.py

# The CPU testbenches drive the DUT with sequences of @(posedge clk) timing
# controls inside initial blocks, which Verilator 4.038 cannot schedule
# ("one timing control per procedure"). They are Icarus-only; lint is scoped
# to the synthesizable checkbenches.
LINT_TESTS := pkg_smoke alu regfile decoder branch_cond

ISA_JSON    := isa/isa.json
GEN_HEADER  := $(GEN_DIR)/decoder_vectors.svh
TOOLS       := tools/isa_tools.py tools/check_pkg_isa.py

SIM_BINS := $(addprefix $(SIM_DIR)/,$(TESTS))

.PHONY: all compile lint sim test docs docs-check isa-check vect clean asm-check \
        $(addprefix run-,$(TESTS)) $(addprefix lint-,$(TESTS)) \
        run-deckos run-deckos-vcd run-cshell-term run-cshell-term-vcd \
        term-check term-check-cshell

all: compile

# ---- generated golden decode vectors ----
vect: $(GEN_HEADER)

$(GEN_HEADER): $(TOOLS) $(ISA_JSON)
	@mkdir -p $(GEN_DIR)
	python3 tools/isa_tools.py vectors $(ISA_JSON) $@

# ---- per-test Icarus simulation binary ----
$(SIM_DIR)/%: $(RTL_SRCS) $(TB_DIR)/%_tb.sv $(GEN_HEADER) $(wildcard $(PROG_DIR)/*_words.svh)
	@mkdir -p $(SIM_DIR)
	$(SIM) $(SIMFLAGS) -I $(GEN_DIR) -I $(TB_DIR) -I $(PROG_DIR) -o $@ $(RTL_SRCS) $(TB_DIR)/$*_tb.sv

# Per-test run/lint targets are generated explicitly (pattern-rule recipes
# for phony goals behave unpredictably in GNU make 4.3). `deckos` is left
# out of the loop because the interactive terminal owns `run-deckos`; its
# deterministic bundle runs as `run-deckos-tb`.
define RUN_mk
.PHONY: run-$(1)
run-$(1): $(SIM_DIR)/$(1)
	$(VVP) $(SIM_DIR)/$(1)
	@echo "PASS:$(1)"
endef
$(foreach t,$(filter-out deckos,$(TESTS)),$(eval $(call RUN_mk,$(t))))

.PHONY: run-deckos-tb
run-deckos-tb: $(SIM_DIR)/deckos
	$(VVP) $(SIM_DIR)/deckos
	@echo "PASS:deckos"

define LINT_mk
.PHONY: lint-$(1)
lint-$(1): $(RTL_SRCS) $(TB_DIR)/$(1)_tb.sv $(GEN_HEADER)
	@mkdir -p $(BUILD_DIR)
	$(VERILATOR) --lint-only -Wall -Wno-fatal -Wno-DECLFILENAME \
		-I$(GEN_DIR) -I$(TB_DIR) -I$(PROG_DIR) -top-module $(1)_tb $(RTL_SRCS) $(TB_DIR)/$(1)_tb.sv \
		>/dev/null 2>$(BUILD_DIR)/lint-$(1).log || \
		{ cat $(BUILD_DIR)/lint-$(1).log; exit 1; }
	@echo "lint:$(1) OK"
endef
$(foreach t,$(TESTS),$(eval $(call LINT_mk,$(t))))

compile: $(SIM_BINS)

lint: $(addprefix lint-,$(LINT_TESTS))
	@echo "verilator lint OK"

sim: $(addprefix run-,$(filter-out deckos,$(TESTS))) run-deckos-tb
	@echo "all simulations OK"

# ---- interactive DeckOS terminal ----
#
# deckos_term_tb is the shared transport behind both the human terminal and
# the deterministic scripted regression: it boots the DeckOS image, forwards
# every UART TX byte to stdout and feeds a host FIFO into the UART RX path
# (+rx=<fifo>). It is deliberately NOT in TESTS (it would block forever
# waiting for input); 'make test' covers the same binary via term-check.

# The VCD build differs only in -DDUMPVCD (the tb then dumps deckos_term.vcd).
$(SIM_DIR)/deckos_term_vcd: $(RTL_SRCS) $(TB_DIR)/deckos_term_tb.sv $(GEN_HEADER) $(PROG_SVHS)
	@mkdir -p $(SIM_DIR)
	$(SIM) $(SIMFLAGS) -DDUMPVCD -I $(GEN_DIR) -I $(TB_DIR) -I $(PROG_DIR) -o $@ $(RTL_SRCS) $(TB_DIR)/deckos_term_tb.sv

run-deckos: $(SIM_DIR)/deckos_term
	python3 sim/terminal/deckcpu_terminal.py $(SIM_DIR)/deckos_term

run-deckos-vcd: $(SIM_DIR)/deckos_term_vcd
	python3 sim/terminal/deckcpu_terminal.py $(SIM_DIR)/deckos_term_vcd

term-check: $(SIM_DIR)/deckos_term
	python3 sim/terminal/deckos_term_test.py $(SIM_DIR)/deckos_term
	@echo "deckos_term: PASS (scripted UART round-trip)"

# ---- interactive DeckC console terminal ----
#
# cshell_term_tb shares the deckos_term transport design (prompt "deckc> ")
# and is deliberately NOT in TESTS (it would block forever waiting for input);
# 'make test' covers the same binary via term-check-cshell.

$(SIM_DIR)/cshell_term_vcd: $(RTL_SRCS) $(TB_DIR)/cshell_term_tb.sv $(GEN_HEADER) $(CSHELL_IMG)
	@mkdir -p $(SIM_DIR)
	$(SIM) $(SIMFLAGS) -DDUMPVCD -I $(GEN_DIR) -I $(TB_DIR) -I $(PROG_DIR) -o $@ $(RTL_SRCS) $(TB_DIR)/cshell_term_tb.sv

run-cshell-term: $(SIM_DIR)/cshell_term
	python3 sim/terminal/deckcpu_terminal.py $(SIM_DIR)/cshell_term

run-cshell-term-vcd: $(SIM_DIR)/cshell_term_vcd
	python3 sim/terminal/deckcpu_terminal.py $(SIM_DIR)/cshell_term_vcd

term-check-cshell: $(SIM_DIR)/cshell_term
	python3 sim/terminal/cshell_term_test.py $(SIM_DIR)/cshell_term
	@echo "cshell_term: PASS (scripted UART round-trip)"

# ---- generated docs from the single source of truth ----
docs:
	python3 tools/isa_tools.py docs $(ISA_JSON) docs

docs-check:
	python3 tools/isa_tools.py docs $(ISA_JSON) $(BUILD_DIR)/docs-check
	@diff -q $(BUILD_DIR)/docs-check/isa.md docs/isa.md >/dev/null || { \
		echo "docs/isa.md is out of date (run 'make docs')"; exit 1; }
	@diff -q $(BUILD_DIR)/docs-check/memory-map.md docs/memory-map.md >/dev/null || { \
		echo "docs/memory-map.md is out of date (run 'make docs')"; exit 1; }
	@echo "generated docs in sync"

# ---- host-side ISA validation and RTL<->spec cross-check ----
isa-check:
	python3 tools/isa_tools.py validate $(ISA_JSON)
	python3 tools/check_pkg_isa.py .

# ---- assembler/disassembler ----
asm-check:
	python3 -m pytest -q $(ASM_TEST)

# ---- deckc CIOS golden image + interpreter/RTL regression ----
$(CIOS_IMG) $(CIOS_HEX): $(CIOS_SRCS)
	python3 tools/gen_cios_image.py

$(CSHELL_IMG) $(CSHELL_HEX): $(CSHELL_SRCS)
	python3 tools/gen_cshell_image.py

build/sim/deckos_c: $(CIOS_IMG) $(CIOS_HEX)

build/sim/cshell: $(CSHELL_IMG) $(CSHELL_HEX)

deckc-check: $(CIOS_IMG) $(CSHELL_IMG)
	python3 -m pytest -q software/deckc/test_deckc.py

test: isa-check docs-check lint sim asm-check deckc-check term-check term-check-cshell
	@echo "================ deckcpu test suite PASSED ================"

clean:
	rm -rf $(BUILD_DIR) obj_dir