// Auto-generated by tools/gen_phase3_programs.py -- do not edit.
// 15 contiguous words from byte 0 (60 bytes).
localparam int CPU_FSM_PROG_NWORDS = 15;
initial begin : prog_words
        PW[0] = 32'h00000000;
        PW[1] = 32'h56000000;
        PW[2] = 32'h57000000;
        PW[3] = 32'h11100008;
        PW[4] = 32'h02210000;
        PW[5] = 32'h40000008;
        PW[6] = 32'h20300063;
        PW[7] = 32'h0A011000;
        PW[8] = 32'h44000008;
        PW[9] = 32'h20300063;
        PW[10] = 32'h45000008;
        PW[11] = 32'h20300064;
        PW[12] = 32'h50010000;
        PW[13] = 32'h51400000;
        PW[14] = 32'h60000000;
    end
