// Auto-generated by tools/gen_programs.py -- do not edit.
// 25 contiguous words from byte 0 (100 bytes).
localparam int IRQ_TB_PROG_NWORDS = 25;
initial begin : prog_words
        PW[0] = 32'h40000018;
        PW[1] = 32'h40000024;
        PW[2] = 32'h4000002C;
        PW[3] = 32'h40000034;
        PW[4] = 32'h4000003C;
        PW[5] = 32'h40000044;
        PW[6] = 32'h20101000;
        PW[7] = 32'h57000000;
        PW[8] = 32'h56000000;
        PW[9] = 32'h40000000;
        PW[10] = 32'h20200001;
        PW[11] = 32'h34210000;
        PW[12] = 32'h58000000;
        PW[13] = 32'h20200002;
        PW[14] = 32'h34210004;
        PW[15] = 32'h58000000;
        PW[16] = 32'h20200003;
        PW[17] = 32'h34210008;
        PW[18] = 32'h58000000;
        PW[19] = 32'h20200004;
        PW[20] = 32'h3421000C;
        PW[21] = 32'h58000000;
        PW[22] = 32'h20200005;
        PW[23] = 32'h34210010;
        PW[24] = 32'h58000000;
    end
