#!/usr/bin/env python3
"""Generate golden test programs + word-loader includes.

For each program you get:
  - sim/programs/<name>.hex          @-addressed byte image (also drives the
                                     assembler golden tests)
  - sim/programs/<name>_words.svh    word list the testbench pokes into RAM
                                     through the write port during reset

$readmemh is avoided for preloading: Icarus delta-loops when it writes a
memory that an always_comb reads (see simple_ram.sv header). The svh payload
is `initial begin : prog_words ... PW[i] = <word>; ... end`, and each
testbench declares `logic [31:0] PW [0:N-1];` then includes the file.
Holes in the address map are filled with NOP words (0x00000000) so the word list
is contiguous from byte 0 for the write-port loader.
"""

from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "sim" / "programs"


def word_at(addr: int) -> str:
    return f"{addr:08X}"


def emit(name: str, words: list[int]) -> None:
    # golden @-addressed byte hex image (big-endian word -> 4 little byte lines)
    hex_lines = []
    for i, w in enumerate(words):
        if w is None:
            continue
        base = i * 4
        for j in range(4):
            hex_lines.append(f"@{base + j:08X} {(w >> (24 - 8 * j)) & 0xFF:02X}")
    (OUT / f"{name}.hex").write_text("\n".join(hex_lines) + ("\n" if hex_lines else ""))

    # word include for the testbench loader; fill holes with NOPs
    n = len(words)
    nops = [0x00000000 if w is None else w for w in words]
    cnt = {0x00: 0x00000000, 0x56: 0x56000000, 0x57: 0x57000000, 0x60: 0x60000000}
    body = "\n".join(f"        PW[{i}] = 32'h{nops[i]:08X};" for i in range(n))
    inc = (
        f"// Auto-generated by tools/gen_programs.py -- do not edit.\n"
        f"// {n} contiguous words from byte 0 ({n * 4} bytes).\n"
        f"localparam int {name.upper()}_NWORDS = {n};\n"
        f"initial begin : prog_words\n{body}\n    end\n"
    )
    (OUT / f"{name}_words.svh").write_text(inc)


# cpu_fsm program (15 words, 0x00..0x38 contiguous).
cpu_fsm_prog = [
    0x00000000,  # 0x00 NOP
    0x56000000,  # 0x04 EI
    0x57000000,  # 0x08 DI
    0x11100008,  # 0x0C LI r1,8
    0x02210000,  # 0x10 ADD
    0x40000008,  # 0x14 CALL 0x08
    0x20300063,  # 0x18 LI r3,99
    0x0A011000,  # 0x1C CMP
    0x44000008,  # 0x20 BEQ 0x08
    0x20300063,  # 0x24 LI r3,99
    0x45000008,  # 0x28 BNE 0x08
    0x20300064,  # 0x2C LI r3,100
    0x50010000,  # 0x30 PUSH
    0x51400000,  # 0x34 POP
    0x60000000,  # 0x38 HALT
]

# cpu_tb program (36 words incl. NOP holes at 0x78/0x7C, bytes 0x00..0x8C).
cpu_tb_prog = [
    0x20100005,  # 0x00 LI r1,5
    0x20200007,  # 0x04 LI r2,7
    0x01312000,  # 0x08 ADD
    0x02412000,  # 0x0C SUB
    0x0A012000,  # 0x10 CMP
    0x04512000,  # 0x14 AND
    0x05612000,  # 0x18 OR
    0x06712000,  # 0x1C XOR
    0x07810000,  # 0x20 NOT
    0x03912000,  # 0x24 MUL
    0x20A01000,  # 0x28 LI r10,0x1000
    0x343A0004,  # 0x2C ST
    0x30BA0004,  # 0x30 LD
    0x11C1000A,  # 0x34 ADDI r1,10
    0x0A011000,  # 0x38 CMP
    0x4400000C,  # 0x3C BEQ 0x0C
    0x20D00064,  # 0x40 LI r13,100
    0x20E000C8,  # 0x44 LI r14,200
    0x22E30000,  # 0x48 MOV
    0x4100003C,  # 0x4C CALL 0x3C
    0x20D00007,  # 0x50 LI r13,7
    0x50010000,  # 0x54 PUSH
    0x51F00000,  # 0x58 POP
    0x20402000,  # 0x5C LI r4,0x2000
    0x2050002A,  # 0x60 LI r5,0x2A
    0x34540000,  # 0x64 ST
    0x20600080,  # 0x68 LI r6,0x80
    0x34640004,  # 0x6C ST
    0x53040000,  # 0x70 WRSP
    0x58000000,  # 0x74 IRET
    None,        # 0x78 hole -> NOP
    None,        # 0x7C hole -> NOP
    0x2070004D,  # 0x80 LI r7,77
    0x60000000,  # 0x84 HALT
    0x20D0002A,  # 0x88 LI r13,42
    0x42000000,  # 0x8C RET
]

# irq_tb program (25 words, bytes 0x00..0x60).
#
# IVT (first 6 of 8 slots):
#   slot 0 @0x00 JMP main (reset entry)
#   slot 1 @0x04 JMP H1 (TIMER)          slot 2 @0x08 JMP H2 (UART_RX)
#   slot 3 @0x0C JMP H3 (UART_TX)        slot 4 @0x10 JMP H4 (GPIO)
#   slot 5 @0x14 JMP H5 (SPI)
#
# main:   0x18 LI r1,0x1000  0x1C DI  0x20 EI  0x24 JMP . (spin).
# The DI/EI pair gives the irq_tb its gating window: an IRQ asserted before
# EI must be held (no entry while FLAGS.I==0), and the entry is taken at the
# S_FETCH right after EI, pushing PC=0x24.
# Each handler Hk stores its id k at [0x1000 + 4*(k-1)] then IRETs, so the
# testbench can tell which slot ran and that the frame was restored.
irq_tb_prog = [
    0x40000018,  # 0x00 slot0 JMP main (0x18)
    0x40000024,  # 0x04 slot1 JMP H1 (0x28)
    0x4000002C,  # 0x08 slot2 JMP H2 (0x34)
    0x40000034,  # 0x0C slot3 JMP H3 (0x40)
    0x4000003C,  # 0x10 slot4 JMP H4 (0x4C)
    0x40000044,  # 0x14 slot5 JMP H5 (0x58)
    0x20101000,  # 0x18 main: LI r1,0x1000
    0x57000000,  # 0x1C DI
    0x56000000,  # 0x20 EI
    0x40000000,  # 0x24 JMP . (spin loop)
    0x20200001,  # 0x28 H1: LI r2,1
    0x34210000,  # 0x2C ST [r1+0] = r2
    0x58000000,  # 0x30 H1: IRET
    0x20200002,  # 0x34 H2: LI r2,2
    0x34210004,  # 0x38 ST [r1+4] = r2
    0x58000000,  # 0x3C H2: IRET
    0x20200003,  # 0x40 H3: LI r2,3
    0x34210008,  # 0x44 ST [r1+8] = r2
    0x58000000,  # 0x48 H3: IRET
    0x20200004,  # 0x4C H4: LI r2,4
    0x3421000C,  # 0x50 ST [r1+12] = r2
    0x58000000,  # 0x54 H4: IRET
    0x20200005,  # 0x58 H5: LI r2,5
    0x34210010,  # 0x5C ST [r1+16] = r2
    0x58000000,  # 0x60 H5: IRET
]

if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    emit("cpu_fsm_prog", cpu_fsm_prog)
    emit("cpu_tb_prog", cpu_tb_prog)
    emit("irq_tb_prog", irq_tb_prog)
    print("wrote", OUT)
    for f in sorted(OUT.glob("*")):
        print(" ", f.name, f.stat().st_size)