#!/usr/bin/env python3
"""Generate Phase-3 golden programs + word-loader includes.

Emits, for each program:
  - sim/programs/<name>.hex          golden byte image, @-addressed (doc; reused
                                     by the Phase-8 assembler checks)
  - sim/programs/<name>_words.svh    word list that a testbench pokes into the
                                     RAM through its write port during reset

Icarus hangs in a delta loop when $readmemh writes a memory that an always_comb
reads and an always_ff writes, so $readmemh cannot be used for preloading in the
Phase-3 testbenches (see simple_ram.sv header). The {name}_words.svh payload is
an `initial begin : prog_words ... PW[i] = {addr}; ... end` block; the testbench
declares `logic [31:0] PW [0:N-1];` and includes the file after the declaration.
Holes in the address map are filled with NOP words (0x00000000) so the word list
is contiguous from byte 0 for the write-port loader.
"""

from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "sim" / "programs"


def word_at(addr: int) -> str:
    return f"{addr:08X}"


def emit(name: str, words: list[int]) -> None:
    # golden @-addressed byte hex image (big-endian word -> 4 little byte lines)
    hex_lines = []
    for i, w in enumerate(words):
        if w is None:
            continue
        base = i * 4
        for j in range(4):
            hex_lines.append(f"@{base + j:08X} {(w >> (24 - 8 * j)) & 0xFF:02X}")
    (OUT / f"{name}.hex").write_text("\n".join(hex_lines) + ("\n" if hex_lines else ""))

    # word include for the testbench loader; fill holes with NOPs
    n = len(words)
    nops = [0x00000000 if w is None else w for w in words]
    cnt = {0x00: 0x00000000, 0x56: 0x56000000, 0x57: 0x57000000, 0x60: 0x60000000}
    body = "\n".join(f"        PW[{i}] = 32'h{nops[i]:08X};" for i in range(n))
    inc = (
        f"// Auto-generated by tools/gen_phase3_programs.py -- do not edit.\n"
        f"// {n} contiguous words from byte 0 ({n * 4} bytes).\n"
        f"localparam int {name.upper()}_NWORDS = {n};\n"
        f"initial begin : prog_words\n{body}\n    end\n"
    )
    (OUT / f"{name}_words.svh").write_text(inc)


# cpu_fsm program (15 words, 0x00..0x38 contiguous).
cpu_fsm_prog = [
    0x00000000,  # 0x00 NOP
    0x56000000,  # 0x04 EI
    0x57000000,  # 0x08 DI
    0x11100008,  # 0x0C LI r1,8
    0x02210000,  # 0x10 ADD
    0x40000008,  # 0x14 CALL 0x08
    0x20300063,  # 0x18 LI r3,99
    0x0A011000,  # 0x1C CMP
    0x44000008,  # 0x20 BEQ 0x08
    0x20300063,  # 0x24 LI r3,99
    0x45000008,  # 0x28 BNE 0x08
    0x20300064,  # 0x2C LI r3,100
    0x50010000,  # 0x30 PUSH
    0x51400000,  # 0x34 POP
    0x60000000,  # 0x38 HALT
]

# cpu_tb program (36 words incl. NOP holes at 0x78/0x7C, bytes 0x00..0x8C).
cpu_tb_prog = [
    0x20100005,  # 0x00 LI r1,5
    0x20200007,  # 0x04 LI r2,7
    0x01312000,  # 0x08 ADD
    0x02412000,  # 0x0C SUB
    0x0A012000,  # 0x10 CMP
    0x04512000,  # 0x14 AND
    0x05612000,  # 0x18 OR
    0x06712000,  # 0x1C XOR
    0x07810000,  # 0x20 NOT
    0x03912000,  # 0x24 MUL
    0x20A01000,  # 0x28 LI r10,0x1000
    0x343A0004,  # 0x2C ST
    0x30BA0004,  # 0x30 LD
    0x11C1000A,  # 0x34 ADDI r1,10
    0x0A011000,  # 0x38 CMP
    0x4400000C,  # 0x3C BEQ 0x0C
    0x20D00064,  # 0x40 LI r13,100
    0x20E000C8,  # 0x44 LI r14,200
    0x22E30000,  # 0x48 MOV
    0x4100003C,  # 0x4C CALL 0x3C
    0x20D00007,  # 0x50 LI r13,7
    0x50010000,  # 0x54 PUSH
    0x51F00000,  # 0x58 POP
    0x20402000,  # 0x5C LI r4,0x2000
    0x2050002A,  # 0x60 LI r5,0x2A
    0x34540000,  # 0x64 ST
    0x20600080,  # 0x68 LI r6,0x80
    0x34640004,  # 0x6C ST
    0x53040000,  # 0x70 WRSP
    0x58000000,  # 0x74 IRET
    None,        # 0x78 hole -> NOP
    None,        # 0x7C hole -> NOP
    0x2070004D,  # 0x80 LI r7,77
    0x60000000,  # 0x84 HALT
    0x20D0002A,  # 0x88 LI r13,42
    0x42000000,  # 0x8C RET
]

if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    emit("cpu_fsm_prog", cpu_fsm_prog)
    emit("cpu_tb_prog", cpu_tb_prog)
    print("wrote", OUT)
    for f in sorted(OUT.glob("*")):
        print(" ", f.name, f.stat().st_size)